version: "3.9"

services:
    viz:
        image: wielgoszinfo/carlaviz:0.9.13-develop
        entrypoint: [ "/bin/bash", "-c", "sleep 15 && ./docker/run.sh" ]
        expose:
            - 8089
        ports:
            - "127.0.0.1:${CARLAVIZ_FRONTEND_MAPPED_PORT:-49164}:8080"
            - "127.0.0.1:${CARLAVIZ_BACKEND_MAPPED_PORT:-49165}:8081"
        volumes:
            - /etc/localtime:/etc/localtime:ro
        environment:
            CARLA_SERVER_HOST: server
            CARLA_SERVER_PORT: ${CARLA_SERVER_PORT:-2000}
        depends_on:
            - server
    client:
        build:
            context: client
            dockerfile: Dockerfile
            args:
                USER_ID: ${USER_ID:-1000}
                GROUP_ID: ${GROUP_ID:-1000}
                USERNAME: carla-rl-client
        image: wielgoszinfo/carla-rl-client:latest
        user: ${USER_ID}:${GROUP_ID}
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ${PWD}/client:/app
            - vscode:/home/carla-rl-client/.vscode-server
            - vscode-insiders:/home/carla-rl-client/.vscode-server-insiders
            - outputs:/outputs
        environment:
            NVIDIA_VISIBLE_DEVICES: all
            NVIDIA_DRIVER_CAPABILITIES: compute,graphics,utility
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          device_ids: [ '${CLIENT_GPU_ID:-0}' ]
                          capabilities: [ 'compute', 'graphics', 'utility' ]
        depends_on:
            - server
            - viz

volumes:
    vscode:
    vscode-insiders:
    outputs:
