version: "3.9"

services:
  server:
    image: carlasim/carla:0.9.11
    entrypoint: ["/bin/bash", "/home/carla/CarlaUE4.sh"]
    command: [
      "-opengl",
      "-carla-rpc-port=2000",
      "-carla-streaming-port=2001",
      "-quality-level=Low",
      "-server"
    ]
    expose:
      - "2000-2002"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      SDL_VIDEODRIVER: offscreen
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,graphics,utility
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['3']
              capabilities: ['compute','graphics','utility']
  viz:
    image: mjxu96/carlaviz:0.9.11
    entrypoint: ["/bin/bash", "-c", "sleep 10 && ./docker/run.sh"]
    expose:
      - 8089
    ports:
      - "127.0.0.1::8080"
      - "127.0.0.1:49165:8081"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      CARLA_SERVER_HOST: server
      CARLA_SERVER_PORT: 2000
    depends_on:
      - server
  client:
    build:
      context: client
      dockerfile: Dockerfile
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
        USERNAME: carla-rl-client
    image: wielgoszinfo/carla-rl-client:latest
    user: ${USER_ID}:${GROUP_ID}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${PWD}/client:/app
      - vscode:/home/carla-rl-client/.vscode-server
      - vscode-insiders:/home/carla-rl-client/.vscode-server-insiders
      - outputs:/outputs
    environment:
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,graphics,utility
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['3']
              capabilities: ['compute','graphics','utility']
    depends_on:
      - server
      - viz

volumes: 
  vscode:
  vscode-insiders:
  outputs: